### ISSUE TITLE
Practica reconocimiento imagenes con ra

### ISSUE THREAD

**Issue by Litzy-12** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-obed-equipo#2]
[PracticaReconocimientoImagen_Litzy_Obed.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-obed-equipo/files/6507239/PracticaReconocimientoImagen_Litzy_Obed.pdf)

**Comment by hiuta** [comment]
Calificado: 20

**Comment by josealfredo79** [comment]
bien hecho y revisado
